name: todo_server
description: A simple gRPC Todo server and client.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fixnum: ^1.0.0
  get_it: ^7.1.4
  grpc: ^3.0.0
  postgres: ^2.3.2
